trigger:
  branches:
    include:
    - main
  paths:
    include:
    - scripts

variables:
- group: vars
- group: secret-vars

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'prdemoappsc'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az deployment group create -g $(rgName) --template-file ./scripts/deploy.json --parameters projectPrefix=$(projectPrefix) PAT=$(PAT)'

